config/routes.rb
Rails.application.routes.draw do

 
  get 'auth/failure'

  get 'auth/callback'

  get 'auth/:provider/callback' => 'auth#callback'

  

  post 'solutions/comments/create' => 'comments#create'

  delete 'comments/destroy' => 'comments#destroy'

  get 'solutions/index' => 'solutions#index'

  get 'solutions/new' => 'solutions#new'

  delete 'solutions/:id' => 'solutions#destroy'

  post 'solutions/create' => 'solutions#create'

  get 'solutions/:id' => 'solutions#show'

  get 'mysolutions' => 'solutions#mysolutions'

  put 'solutions/:id' => 'solutions#update'

  get 'questions/solutions/:id' => 'solutions#show'

  get 'questions/easy' => 'questions#easy'

  get 'questions/medium' => 'questions#medium'

  get 'questions/hard' => 'questions#hard'

  
  get 'questions/:id' => 'questions#show'

  

  get 'signup' => 'users#new', as: :users

  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  resources :solutions do
    member do
      put "like", to: "solutions#upvote"
      put "dislike", to: "solutions#downvote"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end

  root 'main#index'

  get 'about' => 'main#about'

  resources :tags

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_and_belongs_to_many :tags
	has_many :solutions

  def score 
  self.get_upvotes.size - self.get_downvotes.size
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :current_user
	before_action :is_authenticated?

  def show
  	@question = Question.find_by_id params[:id]
  	@solution_count = Solution.where({question_id: @question.id}).count
  	@comment_counts = Comment.count(:group => :solution_id)

	  if(@solution_count === 0)
	  	render plain: "No solutions with this question"
		else
			@solutions = Solution.where({question_id: @question.id}).order(:cached_votes_score => :desc)
			# render plain: @solution_count
		end  	
  end

  def easy
  	@solution = Solution.new
  	@tag = Tag.find_by({name:"easy"})
	  @solution_count = Solution.where({user_id: @current_user.id}).count
	  puts "debug @solution_count " + @solution_count.to_s

	  if(@solution_count === 0)
	  	@question = @tag.questions.limit(1).order("RANDOM()")
		else
			@answered_question_ids = Solution.find_by({user_id: @current_user.id}).question_id
			@question = @tag.questions.where.not(id: @answered_question_ids).limit(1).order("RANDOM()")
		end

		# render plain: @question[0].content
  end

  def medium
  	@solution = Solution.new
  	@tag = Tag.find_by({name:"medium"})
	  @solution_count = Solution.where({user_id: @current_user.id}).count

	  if(@solution_count === 0)
	  	@question = @tag.questions.limit(1).order("RANDOM()")
		else
			answered_question_ids = Solution.find_by({user_id: @current_user.id}).question_id
			@question = @tag.questions.where.not(id: @answered_question_ids).limit(1).order("RANDOM()")
		end

		# render plain: @question[0].content
  end

  def hard
  	@solution = Solution.new
  	@tag = Tag.find_by({name:"hard"})
	  @solution_count = Solution.where({user_id: @current_user.id}).count

	  if(@solution_count === 0)
	  	@question = @tag.questions.limit(1).order("RANDOM()")
		else
			answered_question_ids = Solution.find_by({user_id: @current_user.id}).question_id
			@question = @tag.questions.where.not(id: @answered_question_ids).limit(1).order("RANDOM()")
		end

		# render plain: @question[0].content
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/easy.html.erb
<%= render "partials/nav" %>

<div class="container-fluid">
<a class="hidden" id="difficulty" data="EASY_STATE"></a>
                 <div id="countdown"></div>
            <h3><%= @question[0].content %></h3>
       
    <div class="row">
        <div class="col-xs-6 col-sm-10 col-lg-12">
            <div class="row">
           <%= bootstrap_form_for @solution do |t| %>
              <%= t.text_area :content, label: "INPUT SOLUTION HERE:", :class => 'easy_box' %>
              <%= t.primary %>
              <%= t.hidden_field :question_id, :value => @question[0].id %>
            <% end %>
            <a href="/questions/easy"><button class=
            "btn waves-effect waves-light" id="skip">SKIP</button></a>
            </div>
        </div>
    </div>
</div>

<%= render "partials/footer" %>

app/views/questions/hard.html.erb
<%= render "partials/nav" %>

<div class="container-fluid">
<a class="hidden" id="difficulty" data="HARD_STATE"></a>
      <div id="countdown"></div>
            <h3><%= @question[0].content %></h3>
            
    <div class="row">
        <div class="col-xs-6 col-sm-10 col-lg-12">
            <div class="row">
           <%= bootstrap_form_for @solution do |t| %>
              <%= t.text_area :content, :class => 'hard_box' %>
              <%= t.primary %>
              <%= t.hidden_field :question_id, :value => @question[0].id %>
            <% end %>
            <a href="/questions/hard"><button class=
            "btn waves-effect waves-light" id="skip3">SKIP</button></a>
            </div>
        </div>
    </div>
</div>

<%= render "partials/footer" %>

app/views/questions/medium.html.erb
<%= render "partials/nav" %>

<div class="container-fluid">
<a class="hidden" id="difficulty" data="MEDIUM_STATE"></a>
 <h1>Problem:</h1>
            <h3><%= @question[0].content %></h3>
            <div id="countdown"></div>
    <div class="row">
        <div class="col-xs-6 col-sm-10 col-lg-12">
            <div class="row">
           <%= bootstrap_form_for @solution do |t| %>
              <%= t.text_area :content, :class => 'medium_box' %>
              <%= t.primary %>
              <%= t.hidden_field :question_id, :value => @question[0].id %>
            <% end %>
            <a href="/questions/medium"><button class=
            "btn waves-effect waves-light" id="skip2">SKIP</button></a>
            </div>
        </div>
    </div>
</div>

<%= render "partials/footer" %>

app/views/questions/show.html.erb
<%= render "partials/nav" %>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-6 col-sm-10 col-lg-12">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-6 col-sm-4 col-lg-12">
                        <h2 class="solutions">ALL SOLUTIONS FOR:</h2>
                        <div class="row">
                            <div class="col s12 m12 l12">
                                <div class="card-panel">
                                    <h1>
                                    <%= @question.title%></h1><span><%= @question.content%></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s12 m12 l12">
                    <div class="card-panel">
                        <span>      
                       <h3><% @solutions.each do |solution|  %></h3>       
                         <h4>SOLUTION BY - <%= solution.user.name %></h3>      
                       <a href="/solutions/<%= solution.id %>"><p><%= solution.content %></p></a>      
                     </span>     
                         <%= link_to like_solution_path(solution), method: :put do %>      
                         <button class="btn waves-effect waves-light" id="up">LIKE       
                         <span >(<%= solution.get_upvotes.size  %>)</span></button>        
                     <% end  %>        
                     <%= link_to dislike_solution_path(solution), method: :put do %>       
                         <button class="btn waves-effect waves-light" id="down">DISLIKE       
                         <span >(<%= solution.get_downvotes.size  %>)</span></button>      
                     <% end %>     
                         <a class="btn waves-effect waves-light" id="down" href="/solutions/<%= solution.id %>">COMMENTS       
                         <span >(<%= @comment_counts[solution.id] %>)</span></a>       
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<%= render "partials/footer" %>