config/routes.rb
Rails.application.routes.draw do

 
  get 'auth/failure'

  get 'auth/callback'

  get 'auth/:provider/callback' => 'auth#callback'

  

  post 'solutions/comments/create' => 'comments#create'

  delete 'comments/destroy' => 'comments#destroy'

  get 'solutions/index' => 'solutions#index'

  get 'solutions/new' => 'solutions#new'

  delete 'solutions/:id' => 'solutions#destroy'

  post 'solutions/create' => 'solutions#create'

  get 'solutions/:id' => 'solutions#show'

  get 'mysolutions' => 'solutions#mysolutions'

  put 'solutions/:id' => 'solutions#update'

  get 'questions/solutions/:id' => 'solutions#show'

  get 'questions/easy' => 'questions#easy'

  get 'questions/medium' => 'questions#medium'

  get 'questions/hard' => 'questions#hard'

  
  get 'questions/:id' => 'questions#show'

  

  get 'signup' => 'users#new', as: :users

  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  resources :solutions do
    member do
      put "like", to: "solutions#upvote"
      put "dislike", to: "solutions#downvote"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end

  root 'main#index'

  get 'about' => 'main#about'

  resources :tags

end

app/models/solution.rb
class Solution < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :question


  def score 
  self.get_upvotes.size - self.get_downvotes.size
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :is_authenticated? #, only: [:new, :create]
  before_action :set_solution, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :current_user

  def index
    @question = Question.find(params[:id])
    @solutions = Solution.find_by({question_id: @question.id})
  end

  def update
    t = Solution.find params[:id]
    t.update solution_params
    redirect_to "/mysolutions"
  end

  def new
  end

  def destroy
    Solution.find(params[:id]).delete
    # render :status => :ok 
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  def create
    solution = Solution.create solution_params do |p|
      p.user_id = @current_user.id
      p.save
    end
    if solution.valid?
      redir_url = "/questions/" + solution.question_id.to_s
      flash[:success] = 'Solution posted!'
      redirect_to redir_url
    else
      messages = solution.errors.map { |k, v| "#{k} #{v}" }
      flash[:danger] = messages.join(', ')
      redirect_to new_solution_path
    end
  end

  def show
    @solution = Solution.includes(:question).find_by_id params[:id]
    @new_comment = Comment.new
    @comment_count = Comment.where({solution_id: @solution.id}).count

    if(@comment_count === 0)
      @comments = []
    else
      @comments = Comment.includes(:user).where({solution_id: @solution.id}).order(:cached_votes_score => :desc)
    end

  end

  def mysolutions
    @solutions_count = Solution.where({user_id: @current_user.id}).count
    
    if(@solutions_count === 0)
      @solutions = []
    else
      @solutions = Solution.includes(:question).where({user_id: @current_user.id})
    end

    #@questions = []

    #@solutions.each do |solution|
    #  @questions << solution.question
    #end

    #render :json => @solutions
    #render :json => @questions
  end

  def upvote
    @solution.upvote_from current_user
    redi 
  end

  def downvote
    @solution.downvote_from current_user
    redirect_to :back
  end

  private

  def set_solution
    @solution = Solution.find(params[:id])
    
  end

  def question_params 
    params.require(:question).permit(:id)
  end

  def solution_params
    params.require(:solution).permit(:content, :question_id)
  end

end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/mysolutions.html.erb
<%= render "partials/nav" %>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-6 col-sm-10 col-lg-12">
            <h1>MY SAVED SOLUTIONS</h1><%@solutions.each do |solution|  %><br>
            <div class="row">
                <div class="col s12 m12 l12">
                    <div class="card-panel">
                        <p><strong>PROBLEM:</strong>
                        <br></p>
                        <p class="text"><%= solution.question.content %></p>
                        <p></p><br>
                        <p><strong>SOLUTION:</strong><br>
                        <br>
                        <%= solution.content %></p>
                        <button id="<%= solution.id %>" class="btn waves-effect waves-light delete">DELETE</button>     
  <button class="btn waves-effect waves-light" data-target="#modal<%= solution.id %>" data-toggle="modal" >EDIT</button>      
 <a class="btn waves-effect waves-light" href="/questions/<%= solution.question_id %>">VIEW</a>

             <div id="modal<%= solution.id %>" class="modal">       
 <div class="col-sm-8 col-md-10 col-lg-12">       
       <%= bootstrap_form_for solution do |t| %>       
              <%= t.text_area :content, :rows => 15 %>        
               <%= t.primary %>        
              <%= t.hidden_field :question_id %>      
             <% end %>     
       <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>       
   </div>      
   </div>
                    </div>
                </div>
            </div>
          <%end %>
        </div>
    </div>
</div>

<%= render "partials/footer" %>



 

app/views/solutions/new.html.erb
<h1>Solutions#new</h1>
<p>Find me in app/views/solutions/new.html.erb</p>

app/views/solutions/show.html.erb
<%= render "partials/nav" %>
        
<div class="container-fluid">
<div class="row">
  <div class="col-xs-6 col-sm-10 col-lg-12">
    <h1 id="title">CODEPREP</h1><img src="http://i22.photobucket.com/albums/b315/Doifreakuout14/LOGO.png">

<div class="row">
      <div class="col s12 m12 l12">
        <div class="card-panel">
          <span>
          <h4>Solution - <%= @solution.question.title %></h4>
          <%= @solution.content %>
          </span>
        </div>
      </div>
    </div>



<div class="container-fluid">
    <div class="row">
        <div class="col-xs-6 col-sm-4 col-lg-12">
       <%= bootstrap_form_for(@new_comment, {url: 'comments/create'}) do |t| %>
              <%= t.text_area :content, :rows => 8, label: "LEAVE A COMMENT HERE:" %>
              <%= t.primary %>
              <%= t.hidden_field :solution_id, :value => @solution.id%>
            <% end %>
        </div>
    </div>
</div>


<div class="row">
      <div class="col s12 m12 l12">
        <div class="card-panel">
          <span>
        <% @comments.each do |comment|  %>
    <h3><i><%= comment.user.name %> says..</i></h3>
    <p><%= comment.content %></p>
        <%= link_to like_comment_path(comment), method: :put do %>
            <button class="btn waves-effect waves-light" id="up">LIKE!
            <span >(<%= comment.get_upvotes.size  %>)</span></button>
        <% end  %>
        <%= link_to dislike_comment_path(comment), method: :put do %>
            <button class="btn waves-effect waves-light" id="down">DISLIKE!
            <span >(<%= comment.get_downvotes.size  %>)</span></button>
        <% end %>
    <% end %>
          </span>
        </div>
      </div>
    </div>








</div>
</div>
</div>


<%= render "partials/footer" %>